import BackButton from "@/components/ui/backButton"
import LatticeVisualizer from "@/components/ui/LatticeVisualizer"
import TabbedBox from "@/components/ui/tabBox"
import Image from "next/image";

export default function Glossary() {
    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 px-8 py-12 font-sans text-slate-100 flex flex-col items-center">
            <BackButton />
            <div className="rounded-xl bg-slate-800 p-6 mb-8 mt-10 w-full md:w-3/4" id="latticedef">
                <h2 className="text-3xl mb-4 text-white flex items-center justify-center">What is a Lattice?</h2>
                <div className="flex flex-col gap-6">
                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                        Lattices in cryptography are defined as sets of all integer linear combinations of certain n-dimensional real space basis vectors. Even more simply, a lattice contains every combination that can be formed by adding together integer multiples of the basis vectors. The dimension (n) of the lattice depends on the amount of basis vectors, which consist of n amount of real numbers.
                    </p>
                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                        As the number of basis vectors increases, the lattice gets exponentially more complex. This matters because solving certain computational problems on high-dimensional lattices are believed to be extremely difficult. These problems form the security foundation of modern lattice-based cryptography.
                    </p>
                    <LatticeVisualizer />
                </div>
            </div>

            <div className="rounded-xl bg-slate-800 p-6 mb-8 mt-10 w-full md:w-3/4 flex flex flex-col items-center">
                <TabbedBox
                    id="latticeproblems"
                    title="Lattice-based problems"
                    tabs={[
                        {
                        label: "Shortest Vector Problem (SVP)",
                            content: (
                                <div className="flex flex-col items-center gap-6">
                                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                                        The shortest vector problem is an optimization problem where the goal is to find the shortest non-zero vector within a lattice. In other words, the goal is to find the shortest distance between two points in the lattice. It sounds deceptively simple. For example, take the following two dimensional lattice.
                                    </p>
                                    <figure className="flex flex-col items-center gap-2">
                                        <Image src="/file.svg" width={200} height={300} alt="2D Lattice"/>
                                        <figcaption className="text-sm text-slate-400 italic">
                                            A 2D lattice. Basis vectors are in blue. The shortest vector in red.
                                        </figcaption>
                                    </figure>
                                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                                        Consider a lattice generated by the basis vectors (4,1) and (3,2). The shortest vector is fairly easy to spot; it is a combination of the two basis vectors, (−1,1). While this is easy to spot in two dimensions, finding the shortest vector becomes far more difficult in the hundreds or thousands of dimensions used in cryptography.
                                    </p>
                                </div>
                            ),
                        },
                        {
                        label: "Learning With Errors (LWE)",
                            content: (
                                <div className="flex flex-col items-center gap-6">
                                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                                        Learning with errors is a mathematical problem based on the idea of representing secret information as a set of equations with errors. Suppose we have the following set of equations, with s as the secret information:
                                    </p>
                                    <figure className="flex flex-col items-center gap-2">
                                        <Image src="/file.svg" width={200} height={300} alt="2D Lattice"/>
                                        <figcaption className="text-sm text-slate-400 italic">
                                            Easy to solve equations.
                                        </figcaption>
                                    </figure>
                                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                                        It is trivial to determine that s = 3 using Gaussian Elimination. However, if we add small errors to each equation:
                                    </p>
                                    <figure className="flex flex-col items-center gap-2">
                                        <Image src="/file.svg" width={200} height={300} alt="2D Lattice"/>
                                        <figcaption className="text-sm text-slate-400 italic">
                                            Equations with random errors added.
                                        </figcaption>
                                    </figure>
                                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                                        It becomes significantly more difficult to figure out what s is.
                                    </p>
                                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                                        In cryptography, this concept is expanded into solving for a secret vector hidden in a large system of equations. Each equation contains a small amount of random noise, which prevents standard linear algebra techniques from efficiently revealing the secret.
                                    </p>
                                    <figure className="flex flex-col items-center gap-2">
                                        <Image src="/file.svg" width={200} height={300} alt="2D Lattice"/>
                                        <figcaption className="text-sm text-slate-400 italic">
                                            Equations with random errors added.
                                        </figcaption>
                                    </figure>
                                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                                        It should be noted that the example of LWE given above is for the search version of the problem. The other version (the decision version) is not relevant to any of the algorithms discussed here.
                                    </p>
                                </div>
                            ),
                        },
                        /** 
                        {
                        label: "Short Integer Solution (SIS)",
                            content: (
                                <div className="flex flex-col items-center gap-6">
                                    <p className="flex justify-center text-xl text-slate-300 leading-relaxed">
                                        later
                                    </p>
                                </div>
                            ),
                        }, */  
                    ]}
                />
            </div>
        </div>
    );
}